version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  backend2:
    build:
      context: ./backend
    ports:
      - "8081:8080"

  auth-backend:
    build:
      context: ./auth-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  frontend2:
    build:
      context: ./client_2
    ports:
      - "3001:3000"
    depends_on:
      - backend
